Repository Stock-Trading-Strategies/stock_trading_strategies, pull requests merged in 2024-04, with the labels that each got.

#126 Jose/django/fix response
  django/rules/views.py
Labels: bug

#131 updating rule
  django/rules/urls.py
  django/rules/views.py
Labels: enhancement

#134 fixing deleting rules
  django/rules/urls.py
  django/rules/views.py
Labels: enhancement

#137 fixing url routing for deleting rules
  reactjs/src/pages/rule.js
Labels: bug

#136 adding a check to ensure the user is logged in
  reactjs/src/pages/authedlayout.js
Labels: bug

#140 Jose/react/adjusting rule execution formatting
  reactjs/src/components/rules/CreateRule.js
  reactjs/src/pages/rule.js
Labels: enhancement

#142 fixing the back button not working
  reactjs/src/pages/rule.js
Labels: bug

#132 list transactions
  django/transactions/migrations/0001_initial.py
  django/transactions/models.py
  django/transactions/serializer.py
  django/transactions/urls.py
  django/transactions/views.py
Labels: enhancement

#144 adding initial code to parse out the form rule data
  django/transactions/migrations/0001_initial.py
  django/transactions/models.py
  django/transactions/serializer.py
  django/transactions/urls.py
  django/transactions/views.py
  reactjs/package-lock.json
  reactjs/package.json
  reactjs/src/components/inputs/AsyncDropDown.js
  reactjs/src/components/inputs/DateInput.js
  reactjs/src/components/rules/CreateRule.js
  reactjs/src/pages/rule.js
Labels: enhancement

#154 fixing bug about column truncate
  django/stocks/migrations/0002_alter_stocks_stock_type.py
  django/stocks/models.py
  django/stocks/tests/test_views.py
Labels: bug

#155 applying the migration for users updated field
  django/users/migrations/0005_alter_users_updated.py
Labels: enhancement

#160 access token fix
  reactjs/src/components/Auth.js
Labels: bug

#162 Making updates to have pagination work
  reactjs/src/components/Pagination.js
  reactjs/src/pages/blocks/header.js
  reactjs/src/pages/rule.js
  reactjs/src/pages/rules.js
Labels: enhancement

#145 Caileb/display rule
  reactjs/src/App.js
  reactjs/src/components/Pagination.js
  reactjs/src/components/rules/CreateRule.js
  reactjs/src/components/rules/rule_chart.js
  reactjs/src/pages/authedlayout.js
  reactjs/src/pages/blocks/header.js
  reactjs/src/pages/nopage.js
  reactjs/src/pages/rule.js
  reactjs/src/pages/rules.js
Labels: enhancement

#163 Jose/django/fixing rules job
  django/rules/management/commands/process_rules.py
  django/stocks/models.py
Labels: bug, enhancement

#168 Jose/react/form json rule
  reactjs/package-lock.json
  reactjs/package.json
  reactjs/src/App.js
  reactjs/src/components/Auth.js
  reactjs/src/components/Pagination.js
  reactjs/src/components/rules/CreateRule.js
  reactjs/src/components/rules/rule_chart.js
  reactjs/src/pages/authedlayout.js
  reactjs/src/pages/blocks/header.js
  reactjs/src/pages/blocks/leftnav.js
  reactjs/src/pages/rule.js
  reactjs/src/pages/rules.js
Labels: enhancement

#122 Caileb carter/create rule page
  .github/workflows/react-tests.yml
  django/stocks/tests/test_views.py
  reactjs/package-lock.json
  reactjs/package.json
  reactjs/src/App.js
  reactjs/src/components/inputs/AsyncDropDown.js
  reactjs/src/components/inputs/DateInput.js
  reactjs/src/components/rules/CreateRule.js
  reactjs/src/pages/blocks/leftnav.js
  reactjs/src/pages/rule.js
Labels: enhancement

#169 handlesubmit and handlechange are in createruleform
  reactjs/src/App.js
  reactjs/src/components/Auth.js
  reactjs/src/pages/authedlayout.js
  reactjs/src/pages/rule.js
Labels: enhancement, javascript

#170 fixing missing conditions
  reactjs/src/components/inputs/AsyncDropDown.js
  reactjs/src/components/inputs/DateInput.js
  reactjs/src/components/rules/CreateRule.js
Labels: bug

#146 parsing through the rules logic
  .github/workflows/pylint.yml
  django/rules/jobs/__init__.py
  django/rules/jobs/daily/__init__.py
  django/rules/jobs/hourly/__init__.py
  django/rules/jobs/monthly/__init__.py
  django/rules/jobs/weekly/__init__.py
  django/rules/jobs/yearly/__init__.py
  django/rules/management/__init__.py
  django/rules/management/commands/__init__.py
  django/rules/management/commands/process_rules.py
  django/rules/migrations/0002_rules_last_ran_timestamp.py
  django/rules/migrations/0003_rulejobs_rules_balance_rules_initial_investment_and_more.py
  django/rules/migrations/0004_rules_start_date.py
  django/rules/models.py
  django/rules/serializers.py
  django/stocks/models.py
  django/transactions/models.py
  reactjs/src/components/rules/CreateRule.js
  run_in_containers.sh
Labels: task

#179 Remove Granularity:
  reactjs/src/components/rules/rule_chart.js
  reactjs/src/components/stocks/show_ticker.js
Labels: task, HIGH PRIORITY

#180 updating Caileb's photo
  reactjs/public/images/caileb-carter-150.png
  reactjs/public/images/caileb-carter-2.png
  reactjs/public/images/caileb-carter.png
  reactjs/src/pages/home.js
Labels: task, HIGH PRIORITY

#187 adding the ability to backup and restore the database
  BuildTools/dockerfile-backend
  BuildTools/mysql/01-databases.sql
  run_in_containers.sh
Labels: enhancement

#188 Sequence Bug:
  reactjs/src/pages/rule.js
Labels: bug

#181 Edit Rule:
  reactjs/src/App.js
  reactjs/src/components/inputs/AsyncDropDown.js
  reactjs/src/components/rules/EditRule.js
  reactjs/src/pages/rule.js
Labels: enhancement, task, HIGH PRIORITY

#196 Caileb carter/react/display total balance
  reactjs/src/pages/rules.js
Labels: enhancement

#200 fixing the Assertion 500!=200 error by changing the end_date and oldest_date
  django/stocks/tests/test_views.py
  django/stocks/views.py
Labels: bug
