Repository Stock-Trading-Strategies/stock_trading_strategies, pull requests merged in 2024-05, with the labels that each got.

#189 Jose/django/rule transactions
  .github/workflows/pylint.yml
  BuildTools/crontab
  django/database/.gitignore
  django/rules/management/commands/process_rules.py
  django/rules/models.py
  django/stocks/management/commands/update_metrics.py
  django/stocks/migrations/0003_stockdata_exchange_close_and_more.py
  django/stocks/migrations/0004_alter_stockdata_exchange_gmtoffset.py
  django/stocks/migrations/0005_alter_stockdata_exchange_gmtoffset.py
  django/stocks/migrations/0006_alter_stockdata_timestamp.py
  django/stocks/migrations/0007_remove_stocksearch_stocks_stoc_search__d18376_idx_and_more.py
  django/stocks/migrations/0008_remove_stockdata_stocks_stoc_ticker__f939d5_idx_and_more.py
  django/stocks/migrations/0009_stockdata_day_close_stockdata_day_open.py
  django/stocks/migrations/0010_alter_stockdata_day_close.py
  django/stocks/models.py
  django/transactions/models.py
  django/users/management/__init__.py
  django/users/management/commands/__init__.py
  django/users/management/commands/update_user_profit_growth.py
  reactjs/src/components/stocks/show_ticker.js
Labels: bug, enhancement, HIGH PRIORITY

#185 Caileb-Carter/react/Display-Transactions:
  reactjs/src/pages/rule.js
Labels: task, HIGH PRIORITY

#214 commenting out messages
  django/rules/management/commands/process_rules.py
Labels: bug

#220 updates to the UI to get Jest to pass
  reactjs/src/App.test.js
  reactjs/src/components/Auth.test.js
  reactjs/src/components/auth/LoginForm.js
  reactjs/src/components/auth/RegisterForm.js
  reactjs/src/pages/blocks/unauthed_header.js
Labels: bug

#215 fixing eslint issues and adjustments to rule chart
  reactjs/src/components/rules/rule_chart.js
  reactjs/src/pages/rule.js
Labels: bug, enhancement

#222 setting a default for trading_periods
  django/stocks/models.py
Labels: enhancement
