Repository Stock-Trading-Strategies/stock_trading_strategies, pull requests merged in 2024-03, with the labels that each got.

#82 removing analysts from our app
  django/analysts/__init__.py
  django/analysts/admin.py
  django/analysts/apps.py
  django/analysts/migrations/__init__.py
  django/analysts/models.py
  django/analysts/tests/.gitignore
  django/analysts/urls.py
  django/analysts/views.py
  django/backend/settings.py
  django/backend/urls.py
Labels: invalid

#71 Refactoring Stocks endpoint
  .github/workflows/pycode-coverage.yml
  .github/workflows/pylint.yml
  BuildTools/supervisord/supervisord.conf
  django/auth/views.py
  django/backend/settings.py
  django/backend/urls.py
  django/stocks/management/utils.py
  django/stocks/migrations/0001_initial.py
  django/stocks/migrations/0002_stockdata_stocks_updated_date_and_more.py
  django/stocks/models.py
  django/stocks/serializers.py
  django/stocks/tests/test_views.py
  django/stocks/urls.py
  django/stocks/views.py
  django/users/models.py
  django/users/views.py
  reactjs/src/App.js
  reactjs/src/components/stocks/Show_ticker_news.js
  reactjs/src/components/stocks/findstock.js
  reactjs/src/components/stocks/searchBar.css
  reactjs/src/components/stocks/show_ticker.js
  reactjs/src/pages/show_ticker.js
  run_in_containers.sh
Labels: enhancement

#93 creating the rules app
  django/rules/__init__.py
  django/rules/admin.py
  django/rules/apps.py
  django/rules/migrations/__init__.py
  django/rules/models.py
  django/rules/tests/__init__.py
  django/rules/tests/test_views.py
  django/rules/views.py
Labels: enhancement

#97 models for the rules app
  django/backend/settings.py
  django/rules/migrations/0001_initial.py
  django/rules/models.py
Labels: enhancement

#89 adding rules path
  reactjs/package-lock.json
  reactjs/package.json
  reactjs/src/App.js
  reactjs/src/components/stocks/show_ticker.js
  reactjs/src/pages/blocks/leftnav.js
  reactjs/src/pages/rules.js
Labels: enhancement

#92 making the docker exec mode use interactive tty
  README.md
Labels: documentation, enhancement

#106 adding rules to django/backend/urls
  django/backend/urls.py
Labels: enhancement

#111 adding wireframe for a rule
  reactjs/src/App.js
  reactjs/src/components/rules/rule_chart.js
  reactjs/src/pages/rule.js
Labels: enhancement

#117 fixing transaction queryset error
  django/transactions/views.py
Labels: bug

#118 fixing eslint issues
  reactjs/src/pages/rule.js
Labels: bug

#116 updating the rules to support creation
  django/backend/pagination.py
  django/backend/settings.py
  django/backend/urls.py
  django/rules/admin.py
  django/rules/apps.py
  django/rules/models.py
  django/rules/serializers.py
  django/rules/urls.py
  django/rules/views.py
  django/transactions/__init__.py
  django/transactions/admin.py
  django/transactions/apps.py
  django/transactions/migrations/__init__.py
  django/transactions/models.py
  django/transactions/tests/__init__.py
  django/transactions/urls.py
  django/transactions/views.py
  django/users/models.py
  reactjs/package-lock.json
  reactjs/package.json
  reactjs/src/App.js
  reactjs/src/components/rules/rule_chart.js
  reactjs/src/pages/rule.js
Labels: enhancement

#120 adjusting line ending to be linux based
  .gitattributes
  django/users/serializers.py
  django/users/tests/test_auth.py
  reactjs/src/components/stocks/Show_ticker_news.js
  reactjs/src/pages/news.js
Labels: bug, enhancement

#67 Caileb carter/login function/TDD Auth Test File
  reactjs/src/App.js
  reactjs/src/components/Auth.js
  reactjs/src/components/Auth.test.js
  reactjs/src/components/auth/LoginForm.js
  reactjs/src/components/auth/RegisterForm.js
  reactjs/src/pages/authedlayout.js
Labels: enhancement

#110 creating rules view
  django/backend/pagination.py
  django/backend/settings.py
  django/rules/admin.py
  django/rules/apps.py
  django/rules/models.py
  django/rules/serializers.py
  django/rules/urls.py
  django/rules/views.py
  django/users/models.py
  reactjs/package-lock.json
Labels: enhancement
